apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: test-namespace

commonLabels:
  app: test-app
  environment: test

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: test-deployment 